name = "voxmind-ai"
main = "index.js"
account_id = "87d457528d5b9a5b86ff95f56f1e7ff2"
workers_dev = true
compatibility_date = "2024-03-24"

[env.production]
kv_namespaces = [
  { binding = "KV_VOXMIND", id = "YOUR_KV_NAMESPACE_ID" }
]
