name = "voxmind-ai"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2024-03-24"

[env.production]
kv_namespaces = [
  { binding = "KV_VOXMIND", id = "YOUR_KV_NAMESPACE_ID" }
]
